### ISSUE TITLE
miniprogram-api-typings breaks the global wx namespace

### ISSUE THREAD

**Issue by pecasha** [toyobayashi/jweixin#2]
缺少了wx.env的类型，例如wx.env.USER_DATA_PATH

**Comment by pecasha** [comment]
不对，这个是微信小程序的，因为我项目是uniapp的，混用小程序和公众号的api，这里wx的命名空间被覆盖了

**Comment by toyobayashi** [comment]
@chihai-chuck 请开个仓库提供最小重现。按理讲命名空间应该是会合并的，不存在覆盖的情况。建议tsconfig里编译文件分开写清楚。

**Comment by pecasha** [comment]
@toyobayashi uniapp微信小程序类型声明默认用的是miniprogram-api-typings这个库，我看里面是直接写了declare let wx: WechatMiniprogram.Wx，他们的namespace倒不是用的wx

**Comment by toyobayashi** [comment]
@chihai-chuck miniprogram-api-typings是全局声明，用本仓库的时候就不要往tsconfig里加全局的`jweixin.d.ts`了，直接模块导入找的是`jweixin.module.d.ts`，这没问题吧

**Comment by toyobayashi** [comment]
好吧还真是覆盖了，你有什么解决方案吗？好像无解了，命名空间和变量不能合并，除非这里全部重写去合并 WechatMiniprogram.Wx，但这显然不现实。
